matrix:
  homeserverUrl: "https://matrix.yourdomain.com"
  domain: "yourdomain.com"
  roomId: "!your-room-id:yourdomain.com"
  botUserId: "@mastobot:yourdomain.com"

mastodon:
  accessToken: "your-mastodon-access-token"
  apiUrl: "https://mastodon.yourinstance.com"
